name: 'Solid Guacamole'
description: 'Testing JIRA integration'
inputs:
  pr_title:
    description: The title of the pull request which should contain the JIRA story. #{{ github.event.pull_request.title }}
    required: true
  jira_user:
    description: The email of the jira user.
    required: true
  jira_token:
    description: The API token associated to the user.
    required: true
  jira_url:
    description: The base URL for jira
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
